substitutions:
  device_name: esp32-d-bedroom-csi
  friendly_name: ESP32-D Bedroom CSI

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: "Birchwood_1602"
  password: "Siva@9686770940_1602"
  ap:
    ssid: "${device_name} Fallback"
    password: "fallback456"

api:
  encryption:
    key: "34LXeYYibr/vwEee19jE43lbqhr7zGtdKLvbgMAqOSY="

ota:
  - platform: esphome

logger:
  level: DEBUG
  baud_rate: 115200

status_led:
  pin: GPIO2

